import React from 'react';
import { Link } from 'react-router-dom';
import logo from '../assets/pennyseo-logo.png';
import fivePennyLogo from '../assets/5pennyAi_logo.png';

const TermsPage = () => {
  return (
    <div className="min-h-screen bg-slate-50 font-sans text-slate-900">
      {/* Navigation */}
      <nav className="p-6 max-w-7xl mx-auto flex justify-between items-center">
        <Link to="/" className="flex items-center h-16 overflow-hidden">
          <img
            src={logo}
            alt="PennySEO"
            style={{ width: '220px', maxWidth: 'none', marginLeft: '-15px' }}
            className="object-cover"
          />
        </Link>
        <div className="hidden md:flex items-center gap-2 text-sm font-medium text-slate-500">
          Powered by <img src={fivePennyLogo} alt="5PennyAi" className="h-5 object-contain" />
        </div>
      </nav>

      {/* Content */}
      <main className="max-w-3xl mx-auto px-6 py-12">
        <div className="bg-white rounded-xl border border-slate-200 p-8">
          <h1 className="text-3xl font-extrabold tracking-tight mb-2">Terms of Service</h1>
          <p className="text-sm text-slate-400 mb-8">Last updated: March 24, 2026</p>

          <div className="prose prose-slate max-w-none space-y-6">
            <p>
              Please read these Terms of Service ("Terms") carefully before using PennySEO ("the Service")
              operated by 5PennyAi ("we", "us", or "our").
            </p>

            <h2 className="text-xl font-bold mt-8 mb-3">1. Acceptance of Terms</h2>
            <p>
              By accessing or using PennySEO at https://www.pennyseo.ai, you agree to be bound by these Terms.
              If you do not agree, do not use the Service.
            </p>

            <h2 className="text-xl font-bold mt-8 mb-3">2. Description of Service</h2>
            <p>
              PennySEO is an AI-powered SEO optimization tool that helps online sellers improve their product
              listing visibility through image analysis, keyword generation, and listing optimization. The Service
              provides suggestions and recommendations — final listing decisions remain entirely with the user.
            </p>

            <h2 className="text-xl font-bold mt-8 mb-3">3. Etsy Trademark Notice</h2>
            <p>
              The term "Etsy" is a trademark of Etsy, Inc. This application uses the Etsy API but is not endorsed
              or certified by Etsy, Inc. PennySEO is an independent tool and is not affiliated with, sponsored by,
              or officially connected to Etsy, Inc.
            </p>

            <h2 className="text-xl font-bold mt-8 mb-3">4. Account Responsibilities</h2>
            <p>You are responsible for:</p>
            <ul className="list-disc pl-6 space-y-1">
              <li>Maintaining the confidentiality of your account credentials</li>
              <li>All activities that occur under your account</li>
              <li>Ensuring that your use of the Service complies with applicable marketplace policies</li>
              <li>The accuracy of information you provide</li>
            </ul>

            <h2 className="text-xl font-bold mt-8 mb-3">5. Acceptable Use</h2>
            <p>You agree NOT to:</p>
            <ul className="list-disc pl-6 space-y-1">
              <li>Use the Service for any unlawful purpose</li>
              <li>Attempt to reverse-engineer, decompile, or extract source code from the Service</li>
              <li>Use the Service to generate misleading, fraudulent, or deceptive listing content</li>
              <li>Resell or redistribute SEO data generated by the Service</li>
              <li>Exceed reasonable usage limits or attempt to abuse the Service</li>
            </ul>

            <h2 className="text-xl font-bold mt-8 mb-3">6. Intellectual Property</h2>
            <p>
              The Service, including its original content, features, and functionality, is owned by 5PennyAi and is
              protected by applicable intellectual property laws. SEO suggestions generated for your listings are
              provided for your use in your marketplace listings.
            </p>

            <h2 className="text-xl font-bold mt-8 mb-3">7. AI-Generated Content</h2>
            <p>
              SEO titles, descriptions, tags, and scores generated by PennySEO are AI-assisted suggestions. We do
              not guarantee:
            </p>
            <ul className="list-disc pl-6 space-y-1">
              <li>Specific search ranking improvements</li>
              <li>Accuracy of keyword volume or competition data</li>
              <li>That generated content complies with any specific marketplace's content policies</li>
            </ul>
            <p>
              You are solely responsible for reviewing, editing, and approving any AI-generated content before
              publishing it to your listings.
            </p>

            <h2 className="text-xl font-bold mt-8 mb-3">8. Third-Party Integrations</h2>
            <p>
              The Service integrates with third-party platforms (including Etsy) via their official APIs. We are not
              responsible for:
            </p>
            <ul className="list-disc pl-6 space-y-1">
              <li>Changes to third-party API availability or terms</li>
              <li>Actions taken by third-party platforms on your account</li>
              <li>Data accuracy from third-party data providers</li>
            </ul>

            <h2 className="text-xl font-bold mt-8 mb-3">9. Limitation of Liability</h2>
            <p className="uppercase text-sm">
              To the maximum extent permitted by law, PennySEO and its operators shall not be liable for any
              indirect, incidental, special, consequential, or punitive damages, including but not limited to loss
              of profits, data, or business opportunities, arising from your use of the Service.
            </p>

            <h2 className="text-xl font-bold mt-8 mb-3">10. Termination</h2>
            <p>
              We reserve the right to suspend or terminate your access to the Service at our discretion, with or
              without notice, for conduct that we determine violates these Terms or is harmful to other users or
              the Service.
            </p>

            <h2 className="text-xl font-bold mt-8 mb-3">11. Modifications</h2>
            <p>
              We may modify these Terms at any time. Continued use of the Service after changes constitutes
              acceptance of the updated Terms.
            </p>

            <h2 className="text-xl font-bold mt-8 mb-3">12. Governing Law</h2>
            <p>
              These Terms shall be governed by the laws of the Province of Quebec, Canada, without regard to
              conflict of law provisions.
            </p>

            <h2 className="text-xl font-bold mt-8 mb-3">13. Contact</h2>
            <p>For questions about these Terms, contact us at:</p>
            <p>
              Email: <a href="mailto:support@pennyseo.ai" className="text-indigo-600 hover:underline">support@pennyseo.ai</a><br />
              Website: <a href="https://www.pennyseo.ai" className="text-indigo-600 hover:underline">https://www.pennyseo.ai</a>
            </p>
          </div>
        </div>
      </main>

      {/* Footer */}
      <footer className="py-12 text-center text-slate-400 text-sm">
        © 2026 5PennyAi. All rights reserved. <br />
        <span className="italic">Designed for Etsy Sellers, by AI Enthusiasts.</span>
        <div className="mt-4 space-x-4">
          <Link to="/privacy" className="hover:text-slate-600 underline">Privacy Policy</Link>
          <Link to="/terms" className="hover:text-slate-600 underline">Terms of Service</Link>
        </div>
        <p className="text-xs text-slate-400 mt-4">
          The term "Etsy" is a trademark of Etsy, Inc. This application uses the Etsy API but is not endorsed or certified by Etsy, Inc.
        </p>
      </footer>
    </div>
  );
};

export default TermsPage;
