// AUTO-GENERATED by scripts/build-help-corpus.mjs — DO NOT EDIT BY HAND.
// Rebuild with: node scripts/build-help-corpus.mjs
// Source files: src/content/docs/**/*.md

export const HELP_CORPUS: string = `# General — Getting Started

How to create your first optimized Etsy listing with PennySEO — from Etsy import or a product photo, all the way to a ready-to-copy title, description, and tags.

PennySEO turns your Etsy products into optimized listings — title, description, and tags backed by real search data. No SEO knowledge required.

**What you'll need:** A free PennySEO account. You start with 30 tokens per month.

There are two ways to get started — pick whichever fits your situation.

:::section{label="Path A" title="Import from your Etsy shop"}

If you already have listings on Etsy, this is the fastest way to start.

Go to [My Shop](/docs/etsy-import) from the sidebar and connect your Etsy account. Browse your existing listings, select the ones you'd like to optimize, and click **Import**. Importing is free and doesn't cost any tokens.

Once imported, you can optionally score your existing tags (3 tokens per listing) to see how your current SEO performs. Then [open any listing in the Studio](/docs/studio/analyzing) to optimize it with PennySEO — your product image, title, and category are already filled in.

:::tip
Scoring your existing tags first gives you a Before/After comparison so you can see exactly how much PennySEO improves your listing.
:::

:::

:::section{label="Path B" title="Start from a product photo"}

If you're creating a new listing or don't have an Etsy shop yet, start here.

Go to [SEO Studio](/docs/studio/analyzing) from the sidebar. Upload a product photo and click **"Analyse Design"** (1 token). The AI examines your image and fills in visual details automatically: style, colors, target audience, and more. It also suggests a Theme and Niche for your product.

Select your **Product Type** from the dropdown (or type a custom one). Add any details about your product in the Description field if you'd like — this helps the AI generate better keywords.

:::tip
A clear, well-lit product photo gives the AI more to work with. Lifestyle shots work too.
:::

:::

## Generate SEO keywords

Whether you came from Path A or B, this step is the same. Click **"Generate SEO"** in the Keyword Research section. PennySEO generates keywords backed by real Etsy search volume, competition data, and buyer intent scores.

The AI pre-selects the best 13 keywords for your listing (Etsy's tag limit). You can adjust the selection — check or uncheck any keyword. Look for keywords with high scores, green competition badges, and Smart Badges like **Trending** or **Evergreen**.

Use **"Recalculate Scores"** after changing your selection to see how it affects your listing strength.

:::tip
Hover over any badge or score to see what it means.
:::

## Generate your listing

Once you're happy with your 13 selected keywords, click **"Optimize with AI"** in the Listing Editor section. PennySEO writes an Etsy-optimized title and description using your selected keywords.

Copy your title, description, and tags directly to your Etsy listing using the copy buttons.

:::tip
The Etsy Search Preview shows you exactly how your listing will appear in search results.
:::

## What's next?

:::deflist{icon="ArrowRight"}
- **[Save keywords you like](/docs/lab/favorites)** — Click the star icon on any keyword to save it to your Keyword Bank in the SEO Lab for reuse across listings.
- **[Try the Strategy Tuner](/docs/studio/keywords)** — Adjust the sliders to prioritize reach, competition, buyer intent, and more.
- **[Check your Dashboard](/docs/dashboard)** — Track your shop's overall SEO health and see which listings need attention.
:::

## Token costs at a glance

| Action | Cost |
| --- | --- |
| Import Etsy listings | Free |
| Analyse Design | 1 token |
| Generate SEO Keywords | 3 tokens (2 to re-generate) |
| Generate Listing Draft | 1 token |
| Score Etsy Listing | 3 tokens per listing |

Some actions use your plan's monthly quota instead of tokens: adding custom keywords and adding keywords from your Favorites bank. Check the [Billing page](/docs/billing) for your plan's limits.

You start with 15 free tokens per month. Need more? Visit the [Billing](/docs/billing) page to see plans and token packs.

---

# General — Etsy Import

How to connect your Etsy shop, import existing listings, score their current tags, see Before/After comparisons, and export optimized listings back to Etsy.

If you already sell on Etsy, you don't have to start from scratch. PennySEO connects to your Etsy shop, imports your existing listings, and shows you exactly how your current SEO performs — so you can see the improvement when you optimize.

## Connecting your Etsy shop

Go to **My Shop** from the sidebar. Click **"Connect your Etsy shop"** to authorize PennySEO to access your listings via Etsy's official API. You'll be redirected to Etsy to grant permission, then sent back to PennySEO automatically.

PennySEO only reads your listing data (titles, descriptions, tags, images, and categories). It never modifies anything on Etsy without your explicit action.

## Browsing and importing

Once connected, your Etsy listings appear in a visual grid with thumbnails. Browse through them, select the ones you'd like to work with, and click **Import**.

Importing is free — it doesn't cost any tokens. Each imported listing is saved as an immutable snapshot of your original Etsy data (title, description, tags, image).

Your plan determines how many listings you can import: Free (10), Starter (50), Growth (150), Pro (300).

![Etsy listing import grid showing product thumbnails with status badges and colored bottom borders — Browse and select your Etsy listings for import](/docs/etsy-import-grid.png)

:::tip
Start by importing your best-selling or most-viewed listings. Optimizing what already gets traffic gives you the fastest ROI.
:::

## Scoring your existing tags

After importing, you can optionally score your existing Etsy tags to see how your current SEO stacks up (3 tokens per listing, up to 5 at a time).

Scoring runs your original tags through PennySEO's full analysis pipeline: image analysis, DataForSEO enrichment, AI scoring for relevance and buy intent, and composite strength calculation. The result is a score from 0 to 100 representing your current listing's SEO health.

This step is optional — you can skip straight to the Studio to optimize. But scoring first gives you the Before score you'll need for comparison.

## Before / After comparison

Once you've scored your original tags and then optimized with PennySEO, the Before/After comparison appears. You'll see your original score alongside your new PennySEO score, with a delta showing the improvement.

This comparison is visible in several places: the My Shop page (as a compact table with all your imported listings), and the Keyword Performance header in the SEO Studio when working on an Etsy listing.

The shop stats bar also shows your average improvement across all optimized listings — a useful metric to track your overall progress.

![Before/After comparison table showing original Etsy scores versus PennySEO optimized scores with improvement deltas — Before/After comparison — see exactly how much PennySEO improves your listings](/docs/etsy-before-after.png)

## Opening in the Studio

From any imported listing, click [Open in Studio](/docs/studio/analyzing) to start optimizing. PennySEO pre-fills everything for you: your product image is downloaded and uploaded, your Etsy category is mapped to a PennySEO product type, and your listing is ready for the full SEO workflow.

From there, the process is the same as any other listing: [analyze the design](/docs/studio/analyzing), [generate keywords](/docs/studio/keywords), select your 13 tags, and [generate an optimized listing](/docs/studio/generating).

:::tip
When you open an Etsy listing in the Studio, leave the Description field empty rather than pasting your existing Etsy description. The AI works better with context notes than with marketing copy it might echo back.
:::

## Filtering imported listings

The My Shop page has status filter pills to help you track progress:

:::deflist
- **All** — Every imported listing.
- **Imported** — Listings that have been imported but not yet scored or optimized.
- **Scored** — Listings whose original tags have been scored.
- **Optimized** — Listings that have been fully optimized with PennySEO-generated keywords.
:::

Each listing card shows a colored bottom border matching its status — slate for imported, amber for scored, green for optimized — so you can see your progress at a glance.

## Exporting back to Etsy

After optimizing a listing, you can push your new title, description, and tags back to Etsy directly from PennySEO. Select the listings you want to update and click **Export**. PennySEO updates your Etsy listings via the API — no manual copy-pasting needed.

Export is free and limited to 5 listings at a time.

:::tip
Before exporting, double-check your generated title and description in the Etsy Search Preview. Once exported, the changes go live on Etsy immediately.
:::

---

# General — Dashboard

Dashboard overview — Quick Stats, Pipeline Bar, Next Actions, Shop Health gauges, Recent Listings, and Trending Keywords.

The Dashboard gives you a bird's-eye view of your SEO progress across all your listings. It shows what's working, what needs attention, and what to do next.

![Full PennySEO Dashboard showing Quick Stats, Pipeline Bar, Shop Health gauges, Recent Listings, and Trending Keywords — Your Dashboard — the SEO command center for your shop](/docs/dashboard-full.png)

## Quick Stats

The top row displays four key metrics at a glance:

:::deflist
- **Total Listings** — How many listings you've created or imported in PennySEO.
- **Avg. SEO Score** — The average listing strength across all your scored listings. This is your shop-wide SEO health indicator.
- **Fully Optimized** — How many listings have completed the full pipeline (analyzed, keywords generated, draft created).
- **Tokens Remaining** — Your current token balance (monthly + bonus).
:::

## Pipeline Bar

Below the stats, a horizontal stacked bar shows how your listings are distributed across the five pipeline stages: **New**, **Analyzed**, **SEO Ready**, **Draft Ready**, and **Complete**. Each segment is proportional — so you can immediately see where most of your listings sit and where the bottleneck is.

## Next Actions

The Next Actions section tells you exactly what to do next, prioritized by impact. Each row shows the action, how many listings it applies to, and the token cost.

For example: "5 listings ready for keyword generation — 40 tokens" or "3 listings ready for draft generation — 3 tokens". If the token cost exceeds your current balance, it's highlighted in amber as a heads-up.

Click any action to go directly to the SEO Listings page, filtered to the relevant status.

## Shop Health

The Shop Health card shows your overall SEO performance through gauges:

**Global Strength** — A large radial gauge showing your shop's average listing strength.

Four secondary gauges show the breakdown: **Visibility**, **Relevance**, **Conversion**, and **Competition**. These are averaged across all your scored listings.

Below the gauges, a 30-day score evolution chart tracks how your shop's average strength has changed over time. A trend badge shows whether you're improving or declining, and by how many points.

If any listings need immediate attention (very low scores), a warning banner appears with the count.

## Recent Listings

A table showing your most recently updated listings with thumbnail, product name, keyword count, SEO score, status, date, and an action button to open the listing in the [Studio](/docs/studio/analyzing).

Etsy-imported listings show an orange **"Etsy"** badge on their thumbnail.

## Trending Keywords

A compact section showing keywords from your listings that are currently trending (rising search volume). Each card displays the keyword, volume, and competition — helping you spot opportunities across your shop.

## First-run onboarding

If you're new to PennySEO, the Dashboard shows a welcome screen instead of the regular view. It collects your name (optional), then walks you through the four-step workflow: Upload & Analyze → Generate SEO → Generate Draft → Copy to Etsy.

The onboarding disappears automatically once you create your first listing.

---

# General — Billing & Tokens

Token costs per action, monthly quotas, plan tiers, token packs, the Billing page layout, and a Billing FAQ.

PennySEO uses a token system. Every AI-powered action costs a set number of tokens. You get a monthly token allowance with your plan, and you can buy extra tokens whenever you need them.

## Understanding tokens

Tokens are PennySEO's currency. Each action that uses AI processing or external data has a fixed token cost:

| Action | Cost |
| --- | --- |
| Import Etsy listings | Free |
| Analyse Design | 1 token |
| Generate SEO Keywords | 3 tokens |
| Re-generate SEO Keywords | 2 tokens |
| Generate Listing Draft | 1 token |
| Score Etsy Listing | 3 tokens per listing |

Your token balance is always visible in the sidebar. When it drops below 10, a warning indicator appears. If you run out of tokens mid-workflow, a modal explains your options: wait for your monthly reset or buy a token pack.

## Monthly quotas

Some actions use your plan's monthly quota instead of tokens:

:::deflist{icon="ArrowRight"}
- **Add custom keyword** — Adding a custom keyword to the Keyword Performance table. Each plan has a monthly limit on how many custom keywords you can add.
- **Add from Favorites** — Adding keywords from your Favorite Tags bank to a listing. Also limited by your plan's monthly quota.
:::

Quotas reset at the start of each billing cycle. You can check your current usage on the Billing page.

## Plans

PennySEO offers four plans, available in monthly or yearly billing (save 17% with yearly):

:::deflist{icon="ArrowRight"}
- **Free** — 15 tokens per month. Enough to fully optimize about 3 listings. Good for trying PennySEO and seeing results before committing.
- **Starter** — More tokens and higher quotas for sellers with a small shop. Ideal if you have 10–30 active listings.
- **Growth** — The most popular plan. Designed for active sellers who optimize regularly and have a growing catalog.
- **Pro** — Maximum tokens and quotas for high-volume sellers with large shops.
:::

All plans include the same features — there are no feature gates. The difference is purely in token allowance, monthly quotas, and Etsy import limits.

Visit the [Pricing page](/pricing) for current prices and detailed plan comparisons.

## Token packs

Need more tokens without changing your plan? Token packs are one-time purchases that never expire:

:::deflist{icon="ArrowRight"}
- **50 tokens** — Good for a quick top-up.
- **150 tokens** — Covers a batch of optimizations.
- **500 tokens** — Best value for heavy users.
:::

Purchased tokens are added to your bonus balance, which is separate from your monthly allowance. Monthly tokens are used first — bonus tokens are only consumed after your monthly balance runs out.

## The Billing page

Access the Billing page from the sidebar. It shows:

![Billing page showing current plan, token balance progress bar, usage stats, and transaction history — The Billing page — manage your plan, tokens, and view transaction history](/docs/billing-page.png)

:::deflist
- **Current Plan** — Your active plan with status badge. Click "Manage subscription" to open the Stripe Customer Portal, where you can upgrade, downgrade, cancel, or update payment methods.
- **Token Balance** — A progress bar showing how much of your monthly allowance you've used, plus your bonus token count. A "Buy tokens" button opens the token pack options.
- **Usage Stats** — How many custom keywords and favorite adds you've used this cycle versus your plan's limits.
- **Transaction History** — A paginated log of all token activity: monthly credits, pack purchases, and deductions per action. Color-coded for quick scanning.
:::

## Billing FAQ

:::faq
### When do monthly tokens reset?

At the start of each billing cycle (the day you subscribed). Unused monthly tokens don't carry over.

### Do bonus tokens expire?

No. Tokens purchased through token packs stay in your account until you use them.

### What happens if I downgrade?

Your new token allowance takes effect at the next billing cycle. Bonus tokens are unaffected.

### Can I get a refund?

Subscription management (cancellation, refunds) is handled through the Stripe Customer Portal, accessible from the Billing page.
:::

---

# General — Settings

How to fine-tune SEO Strategy Weights, Smart Badge sensitivity, Analysis Constraints, and manage custom Themes and Niches (My Shop Identity).

The Settings page lets you fine-tune PennySEO's algorithms and manage your personal taxonomy. Most sellers never need to change these — the defaults work well. But if you want more control, it's all here.

![Settings page showing SEO Strategy Weights accordion with segmented controls — Settings — fine-tune how PennySEO ranks and selects keywords](/docs/settings-page.png)

## SEO Strategy Weights

Five sliders that control how PennySEO ranks and selects keywords across all your listings:

:::deflist
- **Volume** — How much weight to give search volume. Higher means the algorithm favors popular keywords.
- **Competition** — How much weight to give competition level. Higher means the algorithm favors keywords that are easier to rank for.
- **Transactional** — How much weight to give buyer intent. Higher means the algorithm favors keywords from people ready to purchase.
- **Niche** — How much weight to give product relevance. Higher means the algorithm favors keywords that closely match your specific product.
- **CPC** — How much weight to give cost-per-click. Higher means the algorithm favors keywords with high commercial value.
:::

Each slider has multiple levels. Changes apply to all future keyword generations and strategy applications. Your existing listings are not affected until you re-generate or apply a new strategy.

:::tip
If you're unsure, leave everything at the default. The defaults are calibrated for a balanced approach that works for most Etsy products.
:::

## Smart Badge Sensitivity

Three controls that determine how strictly PennySEO assigns Smart Badges:

:::deflist
- **Evergreen** — How stable a keyword's volume must be over 12 months to earn the Evergreen badge. Higher sensitivity means fewer keywords qualify.
- **Trending** — How much growth is required to earn the Trending badge. Higher sensitivity means only strongly rising keywords qualify.
- **Promising** — How favorable the competition-to-opportunity ratio must be to earn the Promising badge. Higher sensitivity means fewer keywords qualify.
:::

Adjusting these doesn't change the underlying data — it only changes which keywords get badged. If you're seeing too many (or too few) badges, tweak these thresholds.

## Analysis Constraints

Three numeric settings for advanced users:

:::deflist
- **AI Selection Count** — How many keywords the AI auto-selects after generation. Default is 13 (Etsy's tag limit). You rarely need to change this.
- **Working Pool Size** — How many keywords are kept in the active pool after filtering. A larger pool gives you more options to browse in the Suggestions & Discovery section.
- **Concept Diversity Limit** — How many times the same root concept can appear in your keyword pool. Default is 2. Lower values force more variety; higher values allow more variations of the same term.
:::

## My Shop Identity

Manage your custom themes and niches. Two tabs:

:::deflist{icon="ArrowRight"}
- **My Themes** — Create, edit, and delete custom visual aesthetic categories. Mark favorites with the star icon for quick access in the Studio dropdowns.
- **My Niches** — Create, edit, and delete custom buyer audience categories. Same favorite-star system.
:::

Custom themes and niches appear alongside PennySEO's built-in taxonomy in all dropdown menus throughout the app, including the [Studio](/docs/studio/analyzing). They're scoped to your account — other users don't see them.

---

# General — Understanding Your Scores

Explains every score PennySEO shows — Overall Listing Strength, Visibility, Relevance, Buy Intent, Competition, Est. Value, Reach Index — and how to improve each one.

PennySEO scores your listings across multiple dimensions. This page explains what each score measures, how it's calculated at a high level, and what you can do to improve it.

## Overall Listing Strength (0–100)

This is the big number — your listing's composite SEO score. It combines all the dimensions below into a single measure of how well-positioned your listing is to be found and purchased on Etsy.

Green (80+) means your listing is strong — well-targeted keywords with good volume and manageable competition. Amber (50–79) means you have a solid foundation but room for improvement. Red (below 50) means your listing needs work — likely too many generic or highly competitive keywords.

## Visibility (0–100)

Measures how much search traffic your keyword selection can potentially capture. Driven primarily by the combined search volume of your selected keywords, weighted by relevance and buy intent.

:::howto
Add keywords with higher search volume. But don't chase volume alone — a high-volume keyword you'll never rank for doesn't help. Balance volume with competition.
:::

## Relevance (0–100)

Measures how closely your selected keywords match your specific product. A "personalized dog portrait" keyword is highly relevant to a custom pet portrait listing; a generic "wall art" keyword is less so.

:::howto
Make sure your [Theme, Niche, and Product Type](/docs/studio/analyzing) are accurate. The AI uses these to judge relevance. If they're wrong, relevance scores across all keywords will suffer. Also prefer specific, descriptive keywords over broad generic ones.
:::

## Buy Intent (0–100)

Measures how purchase-ready the people searching your keywords are. Keywords with occasion triggers ("birthday gift for mom"), specific attributes ("sterling silver adjustable ring"), or urgency signals tend to score higher than browsing terms ("jewelry ideas").

:::howto
Include keywords that describe who it's for, when they'd buy it, or why it's special. Gift-related and occasion-specific keywords naturally have higher buy intent.
:::

## Competition (0–100)

Measures how hard it will be to rank for your keyword selection. This is an inverted score — lower competition is better. A low score (green) means your keywords have manageable competition; a high score (red) means many other sellers target the same terms.

:::howto
Swap some high-competition keywords for lower-competition alternatives. Long-tail keywords (3+ words) typically have lower competition. Use the [Strategy Tuner](/docs/studio/keywords) with "Ranking ease" set to High to find these automatically.
:::

## Est. Value

A profitability indicator combining CPC, volume, and competition into a business potential score. Displayed as dollar signs (1–5) rather than a numeric score. More dollar signs means the keyword selection has higher commercial value — advertisers pay more for those search terms, which correlates with buyer willingness to spend.

:::howto
Include keywords with higher CPC values (green in the CPC column). These typically align with purchase-intent terms, so improving Buy Intent often improves Est. Value too.
:::

## Reach Index

A raw visibility number shown as an indigo badge next to Visibility. It represents the AI-weighted probability of your listing being seen, factoring in niche relevance and buyer intent alongside raw volume.

Unlike Visibility (which is a 0–100 score), the Reach Index is an absolute number — useful for comparing different keyword strategies on the same listing.

## Score color coding

Throughout PennySEO, scores follow a consistent color scheme:

:::deflist
- **Green** — Strong performance (80+ for scores, < 0.3 for competition, > $1.50 for CPC).
- **Amber** — Moderate performance (50–79 for scores, 0.3–0.7 for competition, $0.60–$1.49 for CPC).
- **Red / Rose** — Needs improvement (below 50 for scores, > 0.7 for competition, < $0.60 for CPC).
:::

This applies to the Audit Header gauges, keyword table badges, and everywhere else scores appear.

---

# General — FAQ

Common questions about tag count, Smart Badges, low scores, volume thresholds, refresh cadence, Etsy title rules, Theme vs Niche, cross-platform use, data retention, and how PennySEO compares to other tools.

:::faq
### How many tags should I select?

Exactly 13. That's Etsy's maximum, and there's no benefit to using fewer. Every empty tag slot is a missed opportunity to appear in search results. PennySEO's AI pre-selects 13 for you — adjust the selection if you want, but always fill all 13 slots.

### What does Promising mean?

A keyword with the Promising badge has a favorable combination of decent search volume, low competition, and a good opportunity score. These are "hidden gems" — keywords where you have a realistic chance of ranking well without competing against thousands of other sellers.

### Why is my score low?

Usually one of three reasons: your keywords are too generic (low relevance), too competitive (high competition), or too broad (low buy intent). Check the Audit Header breakdown to see which dimension is pulling your score down, then swap keywords accordingly. See the [Understanding Your Scores](/docs/scores) page for specific improvement tips for each dimension.

### Why are some volumes showing "< 10"?

These keywords fall below DataForSEO's measurement threshold. They're typically very long-tail or hyper-niche phrases. Low volume doesn't mean worthless — these keywords often have almost zero competition, making them easy to rank for. They work well as supplementary tags alongside higher-volume keywords.

### Why are some volumes showing "> 1M"?

Extremely high-volume keywords (over 1 million monthly searches) are displayed with a cap. For Etsy sellers, the difference between 1M and 17M searches is strategically irrelevant — both are mass-market terms you're unlikely to rank for as a small seller. The cap avoids implying false precision.

### How often should I refresh my keywords?

Every 2–3 weeks is a good habit. Search trends shift seasonally and with cultural moments. The [SEO Lab](/docs/lab/favorites) flags keywords older than 21 days as "stale." Regular refreshing ensures your data stays accurate and you catch new trends early.

### Does word order matter in Etsy titles?

No. Etsy's search algorithm matches individual words regardless of their position in the title. "Funny Cat Mug Personalized Gift" and "Personalized Gift Funny Cat Mug" perform the same way in search. Focus on including the right words, not arranging them in a specific order.

### What's the difference between Theme and Niche?

Theme describes the visual aesthetic — what your product looks like (e.g., "Minimalist & Clean", "Boho & Organic"). Niche describes the target buyer — who would purchase it (e.g., "Pet Lovers", "Nursing & Healthcare"). A minimalist dog bowl and a rustic dog bowl might share the same Niche (Pet Lovers) but have different Themes.

### Can I use PennySEO for platforms other than Etsy?

PennySEO is optimized specifically for Etsy's search algorithm, tag limits, and marketplace dynamics. The keyword data comes from Etsy search patterns. While the generated titles and descriptions could work on other platforms, the scoring and keyword selection are tailored for Etsy.

### What happens to my data if I cancel?

Your listings, keywords, and presets remain in your account. You can still log in and view everything — you just can't perform token-consuming actions until you resubscribe or buy a token pack. Your data is never deleted because you stopped paying.

### How is PennySEO different from eRank or Marmalead?

PennySEO starts from your product image — not a keyword search box. It uses Vision AI to understand what you're selling, then generates keywords tailored to your specific product. It also writes your complete listing (title + description), not just tag suggestions. And every keyword is scored across multiple dimensions (volume, competition, buy intent, relevance) rather than showing raw data and letting you figure it out.
:::

---

# SEO Lab — Favorite Tags

How the Favorite Tags tab in the SEO Lab works — saving keywords across listings, filtering, grouped views, refreshing stale data, and bulk actions.

The Favorite Tags tab in the SEO Lab is your personal keyword bank — a growing library of keywords you've saved across all your listings. Over time, it becomes your most valuable SEO asset: a curated collection of proven keywords you can reuse, track, and organize into [presets](/docs/lab/presets).

## Saving keywords to your bank

There are two ways to add keywords to your Favorite Tags:

From the [Keyword Performance table](/docs/studio/keywords) in the SEO Studio, click the star icon on any keyword row. It turns gold and the keyword is saved to your bank with all its data (volume, competition, CPC, trend history).

You can also **add keywords manually** directly in the SEO Lab using the inline add row at the top of the table.

Each keyword is stored with its origin context — the theme, niche, and sub-niche from the listing where you first saved it. This helps you filter and organize later.

## Reading the table

The Favorite Tags table shows each keyword with:

:::deflist
- **Tag** — The keyword itself, displayed as a styled pill. Trending and Evergreen indicators appear as small icons next to the tag when applicable.
- **Volume** — Latest monthly search volume from DataForSEO.
- **Trend** — A 12-month sparkline showing the volume trajectory.
- **Competition** — Color-coded score (green, amber, red).
- **CPC** — Cost-per-click value.
- **Niche** — Breadcrumb showing Theme › Niche › Sub-niche context from the original listing.
- **Used In** — How many of your active listings currently use this keyword. An indigo badge for 1–2 listings, green for 3+.
- **Freshness** — When the data was last updated. Keywords older than 21 days are flagged as stale.
:::

You can sort by any column by clicking the header. The table is paginated — choose 10, 25, or 50 rows per page.

![SEO Lab Favorite Tags table with filter pills, keyword tags with trending indicators, and volume data — Your Favorite Tags library with filter pills and keyword data](/docs/seolab-favorites-table.png)

## Filtering your keywords

Use the search bar to find specific keywords by name.

Below the search bar, filter pills let you narrow down your library. Multiple pills can be active at once — they stack with AND logic:

:::deflist
- **All** — No filter, show everything.
- **Gems** — Keywords with high volume, low competition, and good CPC — the best opportunities.
- **Trending** — Keywords with rising search volume.
- **High Volume** — Keywords above a volume threshold.
- **Low Competition** — Keywords with competition below 0.3.
- **Unused** — Keywords not currently used in any of your listings.
- **Stale** — Keywords with data older than 21 days that need refreshing.
:::

For deeper filtering, click the **Filter** button next to the search bar. This opens dropdown filters for Theme, Niche, and Sub-niche. The dropdowns cascade — selecting a Theme narrows the available Niches to only those associated with it.

## Grouped view

Toggle between List view and Grouped view using the segmented control next to the search bar.

Grouped view organizes your keywords into collapsible sections by Theme › Niche, with aggregate stats per group: average volume, average competition, gem count, and usage ratio. This gives you a bird's-eye view of where your keyword strength is concentrated.

![Grouped view showing keywords organized by Theme and Niche with aggregate stats per group — Grouped view organizes your keywords by Theme and Niche](/docs/seolab-grouped-view.png)

## Refreshing stale keywords

Keyword data gets stale over time — search volumes shift, competition changes. Keywords older than 21 days are flagged with a "Stale" indicator.

You can refresh data three ways: individually from the action menu on any stale keyword, in bulk by selecting keywords and using the bulk action bar, or all at once by clicking **"Refresh all stale"** when the Stale filter pill is active.

Refreshing pulls fresh data from DataForSEO — updated volume, competition, CPC, and trend history.

:::tip
Make it a habit to refresh your stale keywords every few weeks. Search trends change, and a keyword that was a gem last month might be saturated now — or vice versa.
:::

## Bulk actions

Select multiple keywords using the checkboxes (the header checkbox selects all on the current page). A sticky action bar appears at the bottom with:

:::deflist
- **Add to Preset** — Bundle the selected keywords into a new or existing preset.
- **Export CSV** — Download your selected keywords as a CSV file.
- **Refresh Stale** — Refresh data for all selected stale keywords at once.
- **Delete** — Remove the selected keywords from your bank.
:::

## Individual actions

Click the three-dot menu on any keyword row for:

:::deflist
- **Copy keyword** — Copy the tag text to your clipboard.
- **Add to preset** — Add this keyword to an existing preset.
- **Refresh data** — Pull fresh data for this keyword (only available when stale).
- **Remove from bank** — Delete this keyword from your Favorites.
:::

---

# SEO Lab — Presets

How to bundle up to 10 keywords from your Favorite Tags into named presets, apply them to listings in one click, and create them directly from the SEO Studio.

Presets let you bundle up to 10 keywords from your [Favorite Tags](/docs/lab/favorites) into a named group that you can apply to any listing with one click. Think of them as keyword recipes — a "Funny Nurse Gifts" preset, a "Minimalist Home Décor" preset, a "Holiday Gift Guide" preset — ready to deploy whenever you need them.

## Creating a preset

Click **"Create Preset"** at the top of the Presets tab. A modal opens where you can:

:::deflist{icon="ArrowRight"}
- **Name your preset** — Give it a descriptive name. Duplicate names are blocked to avoid confusion.
- **Set context** — Optionally assign a Theme, Niche, and Sub-niche using the dropdown menus. This helps you organize presets by category later.
- **Select keywords** — Browse your Favorite Tags bank and check the keywords you want to include (maximum 10). Use the search bar and filter pills (All, Gems, High Volume, Low Competition) to find the right keywords quickly.
:::

A live summary bar at the bottom shows the aggregate stats of your selection: average volume, average competition, and average CPC — so you can gauge the strength of your preset before saving.

![Create Preset modal with keyword selection, filter pills, and live summary stats — Creating a preset — select keywords and see live aggregate stats](/docs/seolab-create-preset.png)

:::tip
Etsy allows 13 tags per listing. Presets cap at 10 to leave room for listing-specific keywords that make each product unique.
:::

## Managing presets

The Presets table shows each preset with sortable columns: name, keyword count, total volume, average competition, and average CPC.

Click any preset row to expand it and see the individual keywords inside, displayed as styled pills. From the expanded view you can:

:::deflist{icon="ArrowRight"}
- **Remove a keyword** — Click the trash icon on any keyword pill to remove it from the preset. Aggregate stats update instantly.
- **Add keywords** — Click the plus button to open a keyword picker and add more keywords from your bank (up to the 10-keyword limit).
- **Edit details** — Inline-edit the preset's name, theme, niche, or sub-niche directly in the table.
:::

![Presets table with an expanded preset showing keyword pills and aggregate stats — A preset expanded to show its keywords and aggregate stats](/docs/seolab-presets-table.png)

## Applying a preset to a listing

Click **"Apply to Listing"** on any preset row. A modal shows your existing listings with their thumbnails, titles, scores, and statuses. Select a listing and confirm — the preset's keywords are added to that listing's keyword pool.

Applied keywords go through the scoring pipeline (niche + transactional scoring) against the target listing's context, so scores may differ from what you see in the SEO Lab.

You can also apply presets from within the SEO Studio. In the [Keyword Performance table](/docs/studio/keywords), click the star icon in the header to open the Favorites picker, switch to the **Presets** tab, and select a preset. Its keywords are added directly to your current listing.

## Creating presets from the Studio

You don't have to build presets in the SEO Lab. While working on a listing in the SEO Studio, click **"Save as Preset"** in the Keyword Performance table header. Your currently selected keywords become the preset's starting pool — the top 10 by volume are pre-selected. The listing's theme, niche, and sub-niche are pre-filled as context.

Keywords that aren't already in your Favorite Tags bank are automatically saved there when the preset is created.

:::tip
After optimizing a listing that performs well, save its keywords as a preset. You can then apply that winning strategy to similar products instantly.
:::

---

# SEO Studio — Analyzing your product

How the SEO Studio extracts visual details from your product image and classifies it into the right theme, niche, and product type so keyword generation has the right context.

Before PennySEO can generate keywords, it needs to understand your product. The analysis step extracts visual details from your photo and classifies your product into the right category.

![Product Studio showing the image upload area, product type selector, and description field — The Product Setup block before analysis — upload your image and select a product type](/docs/studio-product-setup.png)

## Uploading your image

In the SEO Studio, drag and drop a product photo into the upload area, or click to browse your files. You can use product mockups, lifestyle shots, or flat lays — any image that clearly shows what you're selling.

Once your image is uploaded, click **"Analyse Design"** (1 token). The AI examines your photo and fills in six visual fields automatically: Aesthetic Style, Typography, Graphics, Color Palette, Target Audience, and Overall Vibe.

These fields appear in the collapsible **"AI Classification"** section. You don't need to edit them — they're used behind the scenes to generate more relevant keywords. But if something looks off, you can adjust any field manually.

![Analyse Design button with 1 token badge — The Analyse Design button with its token cost badge](/docs/studio-analyse-button.png)

:::tip
The AI works best with images where the product is the main focus. If your photo has a busy background or multiple products, the analysis may be less accurate.
:::

## Theme, Niche, and Sub-niche

The AI also assigns a **Theme**, a **Niche**, and a **Sub-niche** to your product. These are important — they guide the entire keyword generation process.

A **Theme** describes the visual aesthetic of your product — what it looks like. Examples: "Minimalist & Clean", "Boho & Organic", "Sarcastic & Funny".

A **Niche** describes the target buyer — who would buy it. Examples: "Home Décor Enthusiasts", "Pet Lovers", "Nursing & Healthcare".

A **Sub-niche** is a more specific segment within your niche — the kind of search phrase a real Etsy buyer would type. Examples: "Funny Nurse Gifts", "Rustic Farmhouse Signs", "Cat Mom Accessories".

All three are selected from PennySEO's taxonomy. If the AI suggestion doesn't fit, pick a better match from the dropdown. You can also create your own custom themes and niches in [Settings](/docs/settings).

![AI Classification accordion expanded showing visual analysis fields and Theme/Niche/Sub-niche dropdowns — AI Classification section after analysis — visual fields and taxonomy are filled automatically](/docs/studio-ai-classification.png)

:::tip
Getting the Theme and Niche right matters more than any other field. A "Minimalist" mug and a "Vintage" mug will get very different keyword suggestions.
:::

## Product Type

Select your product type from the searchable dropdown — it's grouped by category (Apparel, Drinkware, Home Décor, etc.). If your product doesn't match anything in the list, type a custom name and select **"Use as custom type"**.

Product Type is required before you can generate keywords. It's the most important context the AI uses to ensure keywords are relevant to what you're actually selling.

If you imported your listing from Etsy, the product type is usually pre-filled based on your Etsy category.

## Description field

The Description field is optional but helpful. Use it to tell the AI things it can't see in the photo: materials, dimensions, what makes your product special, who it's for, or how it's used.

You don't need to write a polished description — short notes work fine. For example: "hand-stamped sterling silver, adjustable ring, gift for mom" gives the AI much more to work with than leaving it blank.

:::tip
Don't paste your existing Etsy description here. This field is for context notes that help the AI, not for marketing copy.
:::

## What happens after analysis

Once the analysis is complete, the **"AI Classification"** section expands to show your visual fields, Theme, and Niche. The **"Generate SEO"** button becomes available in the [Keyword Research](/docs/studio/keywords) section below.

Your analysis is saved automatically. If you come back later, everything will be right where you left it — including your image, product type, and all visual fields.

If you want to re-analyze with a different image, simply upload a new one and click **"Analyse Design"** again (1 token).

---

# SEO Studio — Keyword Research

How PennySEO generates keywords with real Etsy search data, how to read the Keyword Performance table, and how to pick the best 13 tags using Smart Badges and the Strategy Tuner.

The Keyword Research section is where PennySEO does its heavy lifting. It generates keywords backed by real Etsy search data, scores them across multiple dimensions, and helps you pick the best 13 tags for your listing.

## Generating keywords

Once your product is [analyzed](/docs/studio/analyzing) (image + product type), click **"Generate SEO"** in the Keyword Research accordion header (3 tokens, or 2 tokens to re-generate).

PennySEO generates keywords across six different angles: core product terms, style and aesthetic variations, buyer and occasion phrases, niche and adjacent categories, long-tail specifics, and broad discovery terms. Each keyword is then enriched with real data from Etsy search: monthly search volume, competition level, cost-per-click, and 12-month volume history.

The AI pre-selects the best 13 keywords — Etsy's maximum tag limit. The Keyword Research section opens automatically when results are ready.

![Keyword Performance table showing keywords with scores, badges, volume, trend sparklines, and selection checkboxes — The Keyword Performance table — your keywords scored and ranked with real Etsy search data](/docs/keywords-table.png)

## Reading the Keyword Performance table

Each row in the table shows one keyword with the following columns:

:::deflist
- **Score** — An overall opportunity score combining all factors. Higher is better.
- **Buy Intent** — How likely someone searching this term is ready to purchase (Very High, High, Moderate, Low). A keyword like "gift for mom birthday" has higher buy intent than "mug ideas".
- **Relevance** — How closely the keyword matches your specific product (Very High, High, Moderate, Low). "personalized dog portrait" is highly relevant to a custom pet portrait; "wall art" is less so.
- **Avg. Volume** — Monthly search volume on Etsy. Displayed as exact numbers for smaller volumes, or rounded labels for large ones (> 50K, > 100K, > 250K, > 500K, > 1M). Keywords below the measurement threshold show "< 10".
- **Trend** — A sparkline showing the 12-month search volume trajectory. Green trending up, red trending down.
- **Competition** — How many other sellers target this keyword (0 to 1). Green (< 0.3) means low competition, amber (0.3–0.7) is medium, red (> 0.7) is high.
- **CPC** — Cost-per-click, reflecting the keyword's commercial value. Green (> $1.50) signals high advertiser demand, which correlates with buyer intent.
- **Status** — Smart Badges assigned automatically based on data patterns.
:::

:::tip
You can sort the table by clicking any column header. Selected keywords always stay pinned at the top.
:::

## Smart Badges

PennySEO automatically tags keywords with badges based on their data patterns:

:::deflist
- :Flame: **Trending** — Search volume is rising significantly. These keywords represent growing demand — good to catch early before competition increases.
- :Leaf: **Evergreen** — Stable, consistent search volume year-round. Reliable traffic sources that won't disappear after a season.
- :Star: **Promising** — Low competition combined with decent volume and a good opportunity score. These are potential "hidden gems" where you can rank more easily.
:::

## Selecting your 13 keywords

Etsy allows a maximum of 13 tags per listing. The AI pre-selects what it considers the best combination, but you have full control.

Check or uncheck any keyword to adjust your selection. Selected keywords are pinned to the top of the table with an indigo highlight. After the 13th selected keyword, a **"Suggestions & Discovery"** divider appears.

Keywords below the divider are your discovery pool — they didn't make the AI's top selection, but they're still scored and available. Browse them for hidden opportunities: a low-competition keyword the AI overlooked, a trending term that fits your product, or a long-tail phrase with strong buy intent. Check any of them to swap them into your selection.

If you select more than 13, a warning appears — you'll need to deselect some before generating your listing draft.

After changing your selection, click **"Recalculate Scores"** to see how your new combination affects the overall listing strength. The Audit Header at the top updates to reflect the scores of your current selection only.

:::tip
A strong selection usually mixes high-volume keywords (for visibility) with low-competition keywords (for ranking) and high buy-intent keywords (for conversions). Don't pick all high-volume — you'll never rank for them.
:::

## The Audit Header

Above the keyword table, the Audit Header gives you a snapshot of your listing's SEO health based on your selected keywords:

:::deflist
- **Overall Score** — The big circular gauge on the left. Green (80+) is strong, amber (50–79) is a good foundation, red (below 50) needs work.
- **Visibility** — How much search traffic your keyword selection can potentially capture. Driven by search volume and reach.
- **Relevance** — How well your keywords match your specific product. Driven by niche scores.
- **Buy Intent** — How purchase-ready the searchers behind your keywords are. Driven by transactional scores.
- **Competition** — How hard it will be to rank for your keyword selection. Lower is better.
- **Est. Value** — A profitability indicator combining CPC, volume, and competition.
:::

Hover over any metric to see a tooltip explaining what your score means and how to improve it.

![Audit Header showing the overall score gauge, visibility, relevance, buy intent, competition metrics, and estimated value — The Audit Header gives you a snapshot of your listing's SEO health](/docs/keywords-audit-header.png)

## Adding more keywords

You can expand your keyword pool in three ways:

:::deflist{icon="ArrowRight"}
- **Add a custom keyword** — Click "+ Add Custom Keyword" at the bottom of the table. Type any keyword and press Enter or click Add. PennySEO fetches real search data and scores it against your listing context. Uses your plan's monthly quota.
- **Add from Favorites** — Click the star icon in the table header to open the Favorites picker. Select keywords you've previously saved to your Keyword Bank. These already have cached data, so no additional API lookup is needed. Uses your plan's monthly quota.
- **Add from a Preset** — In the same Favorites picker, switch to the Presets tab. Select a preset to add all its keywords at once.
:::

Keywords you add appear in the table and are auto-selected. They're marked with a special icon so you can distinguish them from AI-generated keywords.

![Inline custom keyword input row at the bottom of the keyword table — Add a custom keyword directly in the table](/docs/keywords-add-custom.png)

## The Strategy Tuner

For more control, expand the Strategy Tuner accordion between the Audit Header and the keyword table. It has five sliders:

:::deflist
- **Reach** — Prioritize high search volume (more eyes on your listing) vs. lower volume terms.
- **Ranking ease** — Prioritize low competition keywords (easier to rank) vs. competitive ones.
- **Buyer intent** — Prioritize keywords from people ready to buy vs. browsers.
- **Niche specificity** — Prioritize keywords that closely match your exact product vs. broader terms.
- **Market value** — Prioritize keywords with high commercial value (CPC) vs. general terms.
:::

Each slider has four levels: Low, Regular, High, and Aggressive. After adjusting, click **"Apply strategy"** to re-rank your entire keyword pool with the new weights. This doesn't generate new keywords — it re-evaluates and re-selects from your existing pool.

![Strategy Tuner with five sliders at different positions and the Apply strategy button — The Strategy Tuner — adjust weights to re-rank your keyword pool](/docs/keywords-strategy-tuner.png)

:::tip
The default "Regular" setting works well for most products. Try "High" on Ranking ease if you're a new shop with no reviews yet — it helps you target keywords where you can actually compete.
:::

## Saving keywords to your bank

Click the star icon on any keyword row to save it to your [Keyword Bank](/docs/lab/favorites) in the SEO Lab. Saved keywords can be reused across multiple listings, grouped into presets, and tracked over time.

You can also click [Save as Preset](/docs/lab/presets) in the table header to save your current selection as a reusable keyword strategy.

---

# SEO Studio — Generating your listing

How PennySEO writes an Etsy-optimized title and description from your 13 selected keywords, how the Etsy Search Preview works, and how to copy results back to Etsy.

Once you've [selected your 13 keywords](/docs/studio/keywords), PennySEO writes a complete Etsy listing for you — an optimized title and a compelling description that naturally weave in your selected tags.

## Generating the draft

In the Listing Editor section (Section 3), click **"Optimize with AI"** (1 token). PennySEO builds an SEO brief from your selected keywords — including their search volume, badges, and relevance scores — and generates a title and description tailored to your product.

The AI uses your product context as its primary source: visual analysis, product type, theme, niche, and any description notes you provided. If you've set up a Shop Profile with your brand name, tone, and signature, those are incorporated into the sign-off.

Each generation produces a slightly different result. If you're not happy with the output, click **"Optimize with AI"** again (1 token) for a fresh version.

## The title

Your generated title is optimized for Etsy search. A quality bar below the title shows its length: green (120+ characters) means you're using the space well, amber (80–119) is acceptable, and red (under 80) means you're leaving SEO value on the table.

Etsy titles can be up to 140 characters. Word order doesn't matter for Etsy search — the algorithm matches individual words regardless of position. So a title like "Funny Cat Mug - Personalized Gift for Cat Mom - Ceramic Coffee Cup" works just as well as arranging those same words differently.

![Listing Editor showing a generated title with quality bar, generated description, and copy buttons — The Listing Editor with a generated title and description ready to copy](/docs/listing-editor.png)

:::tip
Don't worry about making the title sound like a natural sentence. On Etsy, titles are keyword containers separated by dashes. Buyers scan them, they don't read them like prose.
:::

## The description

Your generated description is written for human readers first, SEO second. It highlights what makes your product special, who it's for, and why someone should buy it — while naturally incorporating your selected keywords.

The description stays concise (150–200 words) and avoids generic filler phrases. If you provided a Shop Profile with a signature line, it appears at the end.

## Etsy Search Preview

Below the title and description, a mini preview card shows how your listing will appear in Etsy search results — with your product thumbnail and the generated title. This gives you a quick visual check before copying anything over.

![Mini Etsy search preview card showing product thumbnail and generated title — See how your listing will look in Etsy search results](/docs/listing-etsy-preview.png)

## Copying to Etsy

Each field has a copy button: title, description, and tags. Click any of them to copy the content to your clipboard, then paste directly into your Etsy listing editor.

Tags are copied as a comma-separated list, ready to paste into Etsy's tag fields.

:::tip
After pasting, save your listing in the Etsy editor and check it in search after a few hours. Etsy's search index updates periodically — give it time before judging your ranking.
:::

## Saving your listing

Click **"Save listing"** to persist your generated title, description, and keyword selection. Your listing moves to the "Complete" status and appears on your Dashboard and in your listing history.

You can always come back to any saved listing from the Dashboard, History, or SEO Listings page to review, regenerate, or adjust keywords.`;

export const HELP_CORPUS_META = {
  "articleCount": 12,
  "totalChars": 55234,
  "builtAt": "2026-05-02T17:29:36.369Z"
} as const;
